json.activity_areas ActivityArea.available_activity_areas
json.available_document_kind_values Document.available_kinds_with_locales
json.available_document_state_values Document.available_states_with_locales
json.doc_tags DocTag.available_doc_tags